branches:
  only:
    - master
git:
  depth: 1
  quiet: true

os: osx
osx_image: xcode10
  
install:
  - mkdir ~/ninja 
  - curl https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip > ninja.zip
  - unzip ninja.zip -d ~/ninja
  - export PATH=~/ninja:$PATH
before_script:
  - mkdir build && cd build
script:
  - cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j $(getconf _NPROCESSORS_ONLN)
  - ctest -j $(getconf _NPROCESSORS_ONLN)
