branches:
  only:
    - master
git:
  depth: 1
  quiet: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0
      - ninja

before_script:
  - mkdir build && cd build
script:
  - cmake -GNinja -DCMAKE_C_COMPILER=clang6.0 -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j $(getconf _NPROCESSORS_ONLN)
  - ctest -j $(getconf _NPROCESSORS_ONLN)
