branches:
  only:
    - master
git:
  depth: 1
  quiet: true
  
cache:
  directories:
    - "~/ninja_and_clang"
  
install:
  - clang --version | sed
  - http://releases.llvm.org/6.0.1/clang+llvm-6.0.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - curl https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip > ninja-linux.zip
  - unzip ninja-linux.zip
  - export PATH=~/ninja:$PATH
before_script:
  - mkdir build && cd build
script:
  - cmake -GNinja -DCMAKE_C_COMPILER=clang-6.0 -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j $(getconf _NPROCESSORS_ONLN)
  - ctest -j $(getconf _NPROCESSORS_ONLN)
