branches:
  only:
    - master
git:
  depth: 1
  quiet: true

os: macos

language: c
compiler: clang

install:
  - brew install ninja
before_script:
  - mkdir build
  - cd build
script:
  - cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j $(getconf _NPROCESSORS_ONLN)
  - ctest -j $(getconf _NPROCESSORS_ONLN)
