branches:
  only:
    - master
git:
  depth: 1
  quiet: true

sudo: required
dist: trusty

language: c

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - clang-6.0

install:
  - mkdir ~/ninja
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip -d ~/ninja
  - export PATH=~/ninja:$PATH
before_script:
  - mkdir build
  - cd build
script:
  - cmake -GNinja -DCMAKE_C_COMPILER=clang6.0 -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j $(getconf _NPROCESSORS_ONLN)
  - ctest -j $(getconf _NPROCESSORS_ONLN)
