branches:
  only:
    - master
git:
  depth: 1
  quiet: true

os: osx
  
install:
  - mkdir ~/clang6
  - curl http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz > clang.tar.xz
  - tar -xf clang.tar.xz -d ~/clang6
  - export PATH=~/clang6:$PATH
  - brew install ninja
before_script:
  - mkdir build && cd build
script:
  - cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j $(getconf _NPROCESSORS_ONLN)
  - ctest -j $(getconf _NPROCESSORS_ONLN)
