branches:
  only:
    - master
    
clone_depth: 1
    
image: Visual Studio 2017

before_build:
  - mkdir C:\ninja
  - cd C:\ninja
  - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  - 7z x ninja-win.zip
  - set PATH=C:\ninja;
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" x64


build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_C_COMPILER="C:/Program Files (x86)/LLVM/bin/clang-cl.exe" -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/LLVM/bin/clang-cl.exe" -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
test_script:
  - ctest . -j2 
