branches:
  only:
    - master
    
clone_depth: 1
    
image: Visual Studio 2017

before_build:
  - mkdir build && cd build
build_script:
  - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_LINKER=lld-link -DCMAKE_BUILD_TYPE=Release -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G "MinGW Makefiles" ..
  - cmake --build .
test_script:
  - ctest . -j2 
