branches:
  only:
    - master
    
clone_depth: 1
    
before_build:
  - ps: mkdir build && cd build
build_script:
  - ps: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..
  - ps: cmake --build .
test_script:
  - ps: ctest . -j2 
