branches:
  only:
    - master
    
clone_depth: 1

image: Visual Studio 2017

before_build:
  - PATH=C:\msys64\usr\bin;%PATH%
  - pacman -S mingw-w64-x86_64-clang --noconfirm
  - set PATH=%APPVEYOR_BUILD_FOLDER%\ninja-binaries\windows;C:\msys64\mingw64\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..
  - ninja -j %NUMBER_OF_PROCESSORS%
test_script:
  - ctest -j %NUMBER_OF_PROCESSORS% 
