branches:
  only:
    - master
    
clone_depth: 1
    
image: Visual Studio 2017

before_build:
  - mkdir C:\ninja
  - cd C:\ninja
  - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip
  - 7z x ninja-win.zip
  - set PATH=C:\ninja;%PATH%

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=clang-cl -DCMAKE_LINKER=lld-link -DCMAKE_BUILD_TYPE=Release -G Ninja ..
  - cmake --build .
test_script:
  - ctest . -j2 
