branches:
  only:
    - master
    
clone_depth: 1
    
image: Visual Studio 2017

before_build:
  - mkdir build && cd build
build_script:
  - cmake -DCMAKE_C_COMPILER:PATH="%ProgramFiles(x86)%\LLVM\bin\clang.exe" -DCMAKE_CXX_COMPILER:PATH="%ProgramFiles(x86)%\LLVM\bin\clang.exe" -DCMAKE_C_COMPILER_ID="Clang" -DCMAKE_CXX_COMPILER_ID="Clang" -DCMAKE_SYSTEM_NAME="Generic" ..
  - cmake --build .
test_script:
  - ctest . -j2 
