branches:
  only:
    - master
    
clone_depth: 1
    
before_build:
  - mkdir build && cd build
build_script:
  - cmake -DCMAKE_C_FLAGS=TRUE -DCMAKE_C_COMPILER=clang -DCMAKE_LINKER=ldd-link -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
test_script:
  - ctest . -j2 
