version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Installing Unzip
          command: sudo apt-get install unzip -y 
      - run:
          name: Installing Ninja
          command: |
            curl https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip  > ninja.zip 
            mkdir ~/ninja
            unzip ninja -d ~/ninja
            export PATH=~/ninja:$PATH
      - run:
          name: Ensuring Out-Of-Tree Build
          command: |
            mkdir build
            cd build
      - run:
          name: Configuring Rylang
          command: cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..
      - run:
          name: Building Rylang
          command: ninja -j $(getconf _NPROCESSORS_ONLN)
      - run:
          name: Testing Rylang
          command: ctest -j $(getconf _NPROCESSORS_ONLN)
