version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: 
          name: Downloading Clang6
          command: |
            mkdir ~/clang6
            curl http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz > clang.tar.xz
            tar -xf clang.tar.xz -d ~/clang6
            export PATH=~/clang6:$PATH
      - run:
          name: Installing Ninja
          command: sudo apt-get install ninja-build
      - run:
          name: Ensuring Out-Of-Tree Build
          command: |
            mkdir build
            cd build
      - run:
          name: Configuring Rylang
          command: cmake -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ..
      - run:
          name: Building Rylang
          command: ninja -j $(getconf _NPROCESSORS_ONLN)
      - run:
          name: Testing Rylang
          command: ctest -j $(getconf _NPROCESSORS_ONLN)
